### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by CMDann** [kreynolds/phidgets-ffi#8]
I am getting an issue using Phidgets and Ruby on my Pi.. 

getting this error:

```
/var/lib/gems/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library '/Library/Frameworks/Phidget21.framework/Versions/Current/Phidget21': /Library/Frameworks/Phidget21.framework/Versions/Current/Phidget21: cannot open shared object file: No such file or directory. (LoadError)
Could not open library '/usr/lib/libphidget21.so': /usr/lib/libphidget21.so: cannot open shared object file: No such file or directory.
Could not open library '/usr/lib64/libphidget21.so': /usr/lib64/libphidget21.so: cannot open shared object file: No such file or directory.
Could not open library '/usr/lib32/libphidget21.so': /usr/lib32/libphidget21.so: cannot open shared object file: No such file or directory.
Could not open library 'Phidget21': Phidget21: cannot open shared object file: No such file or directory.
Could not open library 'libPhidget21.so': libPhidget21.so: cannot open shared object file: No such file or directory.
Could not open library 'libphidget21.so': libphidget21.so: cannot open shared object file: No such file or directory
    from /var/lib/gems/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `map'
    from /var/lib/gems/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `ffi_lib'
    from /var/lib/gems/1.9.1/gems/phidgets-ffi-0.1.3/lib/phidgets-ffi/phidgets-ffi.rb:6:in `<module:FFI>'
    from /var/lib/gems/1.9.1/gems/phidgets-ffi-0.1.3/lib/phidgets-ffi/phidgets-ffi.rb:2:in `<module:Phidgets>'
    from /var/lib/gems/1.9.1/gems/phidgets-ffi-0.1.3/lib/phidgets-ffi/phidgets-ffi.rb:1:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/phidgets-ffi-0.1.3/lib/phidgets-ffi.rb:2:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from HelloWorld.rb:7:in `<main>'
```

**Comment by phidgets** [comment]
You need to download and install the linux library source from phidgets.com http://phidgets.com/ 

## 

Patrick McNeil
Chief Software Architect | Phidgets Inc.

## patrick@phidgets.com | www.phidgets.com

Simplicity is the ultimate sophistication.
-Leonardo da Vinci

**Comment by CMDann** [comment]
I had downloaded that. I had to log out of my user and reinstall it while logged in as the root user. Seems to be working fine now.

**Comment by phidgets** [comment]
Hello!

New message, please read http://sweetchicory.com/form.php?ase

Patrick McNeil

**Comment by phidgets** [comment]
Hi, Do you know what I've just found on the internet? You're gonna be so surprised, just check it out here http://rozevefry.zenmyyoga.net/sleeve.php?t

Regards, Patrick McNeil
